### ISSUE TITLE
Information of night battles won't be shown correctly when both sides deal no damage

### ISSUE THREAD

**Issue by laserdark** [Madmanmayson/BattleInfoPlugin#2]
e.g. One fleet containing 6 SS faces pattern 2/3 on 5-4-I (6/5 SS). 
In such cases, no damage produce, and the plugin won't show even name tables of the enemy. 
When you get into the debug mode, an exception occurred due to the function GetData (line 309) in CommonTypeExtensions.cs whose parameter source = null.
Could you find some ways to fix it, thx.

**Comment by Madmanmayson** [comment]
Well after messing around with 1-5 using a sub in night battles it seems the api response is a little different for night battles then it is for day ones in terms of what is nulled. Adding one more check seems to have fixed it. Assuming you use the english viewer the attached version will work, otherwise you will have to build from the PR branch.

[BattleInfoPlugin (for eng viewer).zip](https://github.com/Madmanmayson/BattleInfoPlugin/files/2045067/BattleInfoPlugin.for.eng.viewer.zip)
